Photash/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^$', home_view, name = 'home'),

    url(r'^home/', include('home.urls', namespace="home")),

    url(r'^photo/', include('photo.urls', namespace="photo")),

    url(r'^contest/', include('contest.urls')),

    url(r'^user/', include('user.urls')),

    url(r'^admin/', admin.site.urls),

    path('api/report-photo/', include('reportedPhotos.api.urls', namespace='reportedPhotos_api')),
    path('api/photo/', include('photo.api.urls', namespace='photo_api')),
    path('api/user/', include('user.api.urls', namespace='user_api')),
    path('api/contest/', include('contest.api.urls', namespace='contest_api')),

    path('oauth/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

contest/api/urls.py
from django.urls import path
from .views import ContestListAPIView, ContestDetailAPIView, VotersListAPIView, FeedAPIView, AskForTags, ContestRankingAPIView, TagDetailAPIView

app_name = 'contest_api'

urlpatterns = [
    path('index/', ContestListAPIView.as_view(), name='index'),
    path('<slug:slug>/detail/', ContestDetailAPIView.as_view(), name='detail'),
    path('<slug:slug>/voters/', VotersListAPIView.as_view(), name='voters'),
    path('<slug:slug>/rankings/', ContestRankingAPIView.as_view(), name='rankings'),
    path('catalogue/', FeedAPIView.as_view(), name='catalogue'),
    path('ask-for-tags/', AskForTags.as_view(), name='ask_for_tags'),
    path('tag/<slug:slug>/', TagDetailAPIView.as_view(), name='tag'),
]

contest/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "contest"

urlpatterns = [

    url(r'^(?P<slug>[\w-]+)/photos/$', contest_photopool, name="photopool"),
    url(r'^(?P<slug>[\w-]+)/upload/$', photo_upload, name="photo_upload"),
    url(r'^index/$', contest_index, name="index"),
    path('tag/<slug:slug>/', tag_search_list, name='tag_search_list'),
    url(r'^(?P<slug>[\w-]+)/$', contest_detail, name='detail'),  # Aslında template içinde bu url çağırılmıyor. Çünkü template içinde url ismini vererek çağırırken parametre vermeyi başaramadım. eğer sonra düzeltirsem diye, url'e de slug koydum.
    # url(r'^create/$', photo_create), CONTEST OLUŞTURMAK ŞİMDİLİK USER TARAFINDAN YAPILAMAYACAGI İÇİN NE FORM NE DE VİEW YAZACAĞIM (SANIRIM)
    url(r'^(?P<id>\d+)/delete/$', contest_delete),
    url(r'^(?P<slug>[\w-]+)/rankings/$', contest_rankings, name='rankings'),

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "home"

urlpatterns = [
    url(r'^catalogue/$', catalogue_view, name='catalogue'),
]

photo/api/urls.py
from django.urls import path
from .views import PhotoListAPIView, PhotoDetailAPIView, api_photo_delete, api_increase_seen_by_one, api_increase_like_by_one

app_name = "photo_api"

urlpatterns = [
    path('<int:id>/', PhotoDetailAPIView.as_view(), name='detail'),
    path('<int:id>/delete/', api_photo_delete, name='delete'),
    path('<slug:slug>/index', PhotoListAPIView.as_view(), name="index_api"),
    path('like/', api_increase_like_by_one, name="like"),
    path('seen/', api_increase_seen_by_one, name='see'),
]

user/api/urls.py
from django.urls import path
from .views import ProfileDetailAPIView, UpdatePreferedTags, read_notification, NotificationsAPIView

app_name = 'user_api'

urlpatterns = [
    path('profile/<int:pk>', ProfileDetailAPIView.as_view(), name='profile'),
    path('update-prefered-tags/', UpdatePreferedTags.as_view(), name='update_prefered_tags'),
    path('notification/', NotificationsAPIView.as_view(), name='notification'),
    path('notification/read/<int:id>', read_notification, name='read_notification'),

]

contest/forms.py
from django import forms
from photo.models import *
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget


class PhotoForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaWidget())
    photo_caption = forms.CharField(max_length=90, widget=forms.TextInput(attrs={'placeholder': 'Enter your caption here'}))
    class Meta:
        model = Photo
        fields = [
            'photoItself',
            'photo_caption'
        ]

contest/api/views.py
from rest_framework import status
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework.views import APIView

from contest.models import Contest, Contender, Tag
from .serializers import ContestSerializer, TagSerializer
from photo.api.serializers import PhotoSerializer
from photo.models import Photo
from user.models import Profile
from user.api.serializers import ProfileSerializer

from django.utils import timezone

from django.shortcuts import get_object_or_404

from random import randint, shuffle, choice
import operator
import math


def recommendation(queryset, user):
    user = Profile.objects.get(user=user)
    preferd_tags = user.prefered_tags.all()
    reordered_queryset = {}
    return_queryset = []

    for query in queryset:
        similarity = 0
        for query_tag in query.tag.all():
            if query_tag in preferd_tags:
                similarity += 1

        try:
            index = similarity / query.tag.all().count()
        except ZeroDivisionError:
            index = 0
        reordered_queryset[query] = index

    reordered_queryset = sorted(reordered_queryset.items(), key=operator.itemgetter(1))
    print(reordered_queryset)

    for query_with_index in reversed(reordered_queryset):
        return_queryset.append(query_with_index[0])

    return return_queryset


class ContestListAPIView(ListAPIView):
    queryset = Contest.objects.all()
    serializer_class = ContestSerializer
    pagination_class = PageNumberPagination

    def get_queryset(self):
        if self.request.GET.get('q') or self.request.GET.get('ongoing') or self.request.GET.get(
                'finished') or self.request.GET.get('upcoming'):
            queryset = self.queryset.all()
            if self.request.GET.get('q'):
                query = self.request.GET['q']
                queryset = queryset.filter(contest_name__icontains=query)

            if self.request.GET.get('ongoing') and not self.request.GET.get('finished') and not self.request.GET.get(
                    'upcoming'):
                copy_queryset = queryset
                queryset = []
                for query in copy_queryset:
                    if not query.is_finished() == True and not query.is_finished() == None:
                        queryset.append(query)

            elif self.request.GET.get('finished') and not self.request.GET.get('ongoing') and not self.request.GET.get(
                    'upcoming'):
                copy_queryset = queryset
                queryset = []
                for query in copy_queryset:
                    if query.is_finished() == True:
                        queryset.append(query)

            elif self.request.GET.get('upcoming') and not self.request.GET.get('ongoing') and not self.request.GET.get(
                    'finished'):
                copy_queryset = queryset
                queryset = []
                for query in copy_queryset:
                    if query.is_finished() == None:
                        queryset.append(query)

        else:
            queryset = super(ContestListAPIView, self).get_queryset()

        if self.request.user.is_authenticated:
            queryset = recommendation(queryset, self.request.user)

        return queryset

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            data = serializer.data
            for x in data:
                x['photo_count'] = Photo.objects.filter(contest=Contest.objects.get(id=int(x['id']))).count()

            return self.get_paginated_response(data)

        serializer = self.get_serializer(queryset, many=True)
        data = serializer.data
        for x in data:
            x['photo_count'] = Photo.objects.filter(contest=Contest.objects.get(id=int(x['id']))).count()


        return Response(data)


class ContestDetailAPIView(RetrieveAPIView):
    queryset = Contest.objects.all()
    serializer_class = ContestSerializer
    lookup_url_kwarg = 'slug'
    lookup_field = 'slug'

    def retrieve(self, request, *args, **kwargs):
        contest = self.get_object()
        photos = Photo.objects.filter(contest=contest)
        serializer = self.get_serializer(contest)
        data = serializer.data

        count_photos = photos.count()
        if count_photos > 2:
            data['examples'] = []
            random_index = randint(0, math.floor(count_photos/3)-1)
            random_index2 = randint(math.floor(count_photos/3), math.floor(2*count_photos/3)-1)
            random_index3 = randint(math.floor(2*count_photos/3), count_photos-1)

            data['examples'].append(PhotoSerializer(photos[random_index]).data)
            data['examples'].append(PhotoSerializer(photos[random_index2]).data)
            data['examples'].append(PhotoSerializer(photos[random_index3]).data)

        data['photo_count'] = count_photos
        data['is_finished'] = contest.is_finished()

        if request.user.is_authenticated:
            try:  # if there is not any Contender object, get() will raise an exception
                contender = Contender.objects.get(user=request.user, contest=self.get_object())
                # context['contender'] = contender
                data['num_of_uploaded_photos'] = contender.get_number_of_photos_uploaded()
                # context['is_uploaded'] = 1  # True
            except Contender.DoesNotExist:
                data['num_of_uploaded_photos'] = 0
                # context['is_uploaded'] = 0  # False

        return Response(data, status=status.HTTP_200_OK)


class VotersListAPIView(RetrieveAPIView):
    queryset = Contest.objects.all()
    serializer_class = ContestSerializer
    permission_class = IsAuthenticated
    authentication_class = SessionAuthentication
    lookup_url_kwarg = 'slug'
    lookup_field = 'slug'

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        if timezone.now() < instance.end_date:
            return Response({'error': 'This contest has not come to an end yet! End date is {}'.format(instance.end_date)})
        try:
            _ = Contender.objects.get(contest=instance, user=request.user)
        except Contender.DoesNotExist:
            return Response({'error': 'You are not a contender for this contest!'}, status=status.HTTP_403_FORBIDDEN)

        data = self.get_serializer(instance).data
        data['photos'] = []

        photos = Photo.objects.filter(contest=instance, ownername=request.user)

        for photo in photos:
            user_list = []
            for user in photo.likes.all():
                user_list.append(ProfileSerializer(Profile.objects.get(user=user)).data)
            photo_data = PhotoSerializer(photo).data
            photo_data['liked_users'] = user_list
            data['photos'].append(photo_data)

        return Response(data, status=status.HTTP_200_OK)


class FeedAPIView(APIView):
    authentication_classes = (SessionAuthentication, TokenAuthentication)
    permission_classes = (IsAuthenticated,)
    http_method_names = [u'get', ]
    queryset = Contest.objects.all()
    paginate_by = 10

    def get_queryset(self):
        if self.queryset.count() < 3:
            limit = self.queryset.count()
        else:
            limit = 3

        integers = list(range(limit))
        queryset = []
        while len(integers) > 0:
            random_integer = choice(integers)
            query = self.queryset[random_integer]
            if Photo.objects.filter(contest=query).count() > 0:
                queryset.append(query)
            integers.remove(random_integer)

        return queryset

    def get(self, request, format=None):
        data = ContestSerializer(self.get_queryset(), many=True).data

        for contest_data in data:
            contest = Contest.objects.get(id=contest_data['id'])
            photos = Photo.objects.filter(contest=contest)
            if photos.count() > 3:
                random_integer = randint(0, photos.count() - 4)
                add = 3
            else:
                random_integer = 0
                add = photos.count()

            start_index = random_integer
            finish_index = random_integer + add
            photo_data = PhotoSerializer(photos[start_index:finish_index], many=True).data

        return Response(photo_data, status=status.HTTP_200_OK)


class AskForTags(ListAPIView):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    authentication_classes = (SessionAuthentication, TokenAuthentication)
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        queryset = super(AskForTags, self).get_queryset()
        return queryset[:15]


class ContestRankingAPIView(ListAPIView):
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer
    authentication_classes = (SessionAuthentication,)

    def get_queryset(self):
        sorted_queryset = {}

        queryset = super(ContestRankingAPIView, self).get_queryset()
        contest = get_object_or_404(Contest, slug=self.kwargs['slug'])

        contenders = Contender.objects.filter(contest=contest)
        excluded_contender_ids = []

        '''for contender in contenders:
            if not contender.check_conditions_for_rankings():
                excluded_contender_ids.append(contender.id)'''

        photos = queryset \
            .filter(contest=contest) \
            .exclude(ownername__contender__id__in=excluded_contender_ids)

        for photo in photos:
            try:

templates/contest/contest_ended.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Too Late...{% endblock %}

{% block body %}
    <div class="container" style="margin-top: 100px;">
        <h1 class="display-2"> Too Late... </h1><br>
        <p>You can not send a photo to this contest because the contest has ended. Don't be late next time! :)</p>
        <form style="display: inline;" action="{% url "contest:index" %}">
            <input class="btn btn-primary btn-lg" type="submit" value="Click to go to explore more contests!">
        </form>
    </div>
{% endblock %}

templates/contest/contest_still_in_progress.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Rankings{% endblock %}

{% block body %}
    <div class="container" style="margin-top: 100px;">
        <h1 class="display-2"> Not so fast cowboy! </h1><br>
        <p>Contest is still in progress, come back here when the contest ends.</p>
        <form style="display: inline;" action="{% url "contest:detail" slug=contest.slug %}">
            <input class="btn btn-primary btn-lg" type="submit" value="Click to go to contest detail page">
        </form>
    </div>
{% endblock %}

templates/contest/detail-tr.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Contest Features{% endblock %}

{% block body %}

<section id= "contest-detail-section" class="contest-detail-sec">
  <div class="inner-more">
      <div class="container">
          <div class="row">
              <div class="col-lg-6 img-col">
                  <div class="contest-img-wrap">
                      <img id="topic-photo" src="">
                  </div>
              </div>

              <div class="col-lg-6 contest-detail-col">
                  <div class="contest-detail-content-wrap">
                      <table class="table table-hover">
                          <tbody>
                              <tr>
                                  <th>Yarışma İsmi</th>
                                      <td id="cname">value["contest_name"]</td>
                              </tr>
                              <tr>
                                  <th>Başlangıç Tarihi</th>
                                      <td class="contest-start-date"> contestStartDate </td>
                              </tr>
                              <tr>
                                  <th>Bitiş Tarihi</th>
                                      <td class="contest-end-date">contestEndtDate</td>
                              </tr>
                              <tr>
                                  <th>Ödül Dağılımı</th>
                                      <td>
                                          <button id="prize-open-btn" class="btn-txt-only"><i class="fa fa-chevron-down"></i></button>
                                              <ul class="prize-list">
                                                  <li></li>
                                                  <li></li>
                                                  <li></li>
                                                  <li></li>
                                              </ul>
                                      </td>
                              </tr>
                              <tr class="tr-btn-wrap">
                                  <th>Ayrıntılar</th>
                                      <td><button id="mini-detail-open-btn" class="btn-txt-only"><i class="fa fa-chevron-down"></i></button></td>
                              </tr>

                          </tbody>
                      </table>
                      <div id="contest-details-wrap-mini">
                          <table class="table table-mini-details">
                              <tbody>
                                  <tr>
                                      <th>Görmeniz gereken minimum fotoğraf sayısı</th>
                                          <td id="min-seen-photos"></td>
                                  </tr>
                                  <tr>
                                      <th>Havuzdaki fotoğraf sayısı</th>
                                          <td id="how-many-photos"></td>
                                  </tr>
                                  <tr>
                                      <th>Yükleyebileceğiniz maksimum fotoğraf sayısı</th>
                                          <td id="max-photos"></td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                      <div class="button-wrap">
                          {% if request.user.is_authenticated %}
                              <form action='{% url 'contest:photo_upload' slug=contest.slug %}'>
                                  <input class="btn btn-fill" type="submit" value="Yükle">
                              </form>
                          {% endif %}
                              <form action='{% url 'contest:photopool' slug=contest.slug %}'>
                                  <input class="btn btn-fill" type="submit" value="Havuz">
                              </form>
                              <form action='{% url 'contest:rankings' slug=contest.slug %}'>
                                  <input id="rankings" class="btn btn-fill" type="submit" value="Sıralamalar" data-toggle="tooltip" title="Rankings will be visible after the contest ends">
                              </form>
                      </div>
                      <div class="contest-tags-wrap">
                          <div class="tags-wrap"></div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

<section style="margin-bottom: 50px;" class="examples">
    <div class="container">
        <div class="examples-top">
            <h3>Havuzdan örnek fotoğraflar</h3>
        </div>
        <div class="examples-content">
            <div class="row">
                    <div class="col-sm-4">
                        <div id="card1" class="card" style="border-color: black;">
                            <img src="" alt="Example Photo" style="width: 350px; height: 200px;">
                        </div>
                    </div>
                    <div id="card2" class="col-sm-4">
                        <div class="card" style="border-color: black;">
                            <img src="" alt="Example Photo" style="width: 350px; height: 200px;">
                        </div>
                    </div>
                    <div id="card3" class="col-sm-4">
                        <div class="card" style="border-color: black;">
                            <img src="" alt="Example Photo" style="width: 350px; height: 200px;">
                        </div>
                    </div>
            </div>
        </div>
    </div>
</section>

<script>

    $(document).ready( function(){

        $.ajax({
            url: '{% url 'contest_api:detail' slug=contest.slug %}',
            type: 'get',
            success: function(value){
                console.log(value);
                $(".cname").text(value["contest_name"]);

                var tagAsStr = '';
                $.each(value['tag'], function(index, data){
                      tagAsStr += "#" + data.title + " ";
                });

                var getContestStartDate = new Date(value["start_date"]);  // Get Contest End Date in ISO Format
                var getContestEndDate = new Date(value["end_date"]);  // Get Contest Start Date in ISO Format
                year = [getContestStartDate.getFullYear() , getContestEndDate.getFullYear()]
                month = [getContestStartDate.getMonth(), getContestEndDate.getMonth()]
                dt = [getContestStartDate.getDate(), getContestEndDate.getDate()]

                //add 0 if date,months are not 2 digits
                if (dt<10) {
                  dt = '0' + dt;
                }

                var monthNames = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"];  //Change month number to String
                contestStartDate = dt[0] + ' ' + monthNames[month[0]] + ' ' + year[0];  //COnverted to Short Date Format,
                contestEndDate = dt[1] + ' ' + monthNames[month[1]] + ' ' + year[1];  //COnverted to Short Date Format

                $("#topic-photo").attr("src",value['topic_photo']);
                $("#cname").html(value['contest_name']);
                $(".contest-start-date").html(contestStartDate);
                $(".contest-end-date").html(contestEndDate);
                $("#min-seen-photos").html(value['min_seen_photos']);
                $("#how-many-photos").html(value['photo_count']);
                $("#max-photos").html(value['max_photos_per_Reguser']);
                $(".tags-wrap").html(tagAsStr);

                //Prize distribution string manipulation and placing
                var arr = value['prize_distributions'].split("\n");
                $(".prize-list li:nth-child(1)").html(arr[0]);
                $(".prize-list li:nth-child(2)").html(arr[1]);
                $(".prize-list li:nth-child(3)").html(arr[2]);
                $(".prize-list li:nth-child(4)").html(arr[3]);

                //Checking if the contest is ended or not in order to decide to disable rankings button
                if(value['is_finished']!=true)
                    $("#rankings").attr("disabled", "true");

                //Arranging random photos from photopool
                $("#card1 img").attr("src",value['examples'][0]['photoItself']);
                $("#card2 img").attr("src",value['examples'][1]['photoItself']);
                $("#card3 img").attr("src",value['examples'][2]['photoItself']);


                $(document).ready(function(){
                  
                  var val = 1;
                  $(".contest-detail-content-wrap .contest-tags-wrap>.btn-txt-only").click(function(){
                      if (val === 1) {
                          $(this).siblings('.form-report').show();
                          val = 0;
                      }
                      else {
                          val = 1;
                          $(this).siblings('.form-report').hide();
                      }
                      return false;
                    });
                

                $("#mini-detail-open-btn").click(function(){
                      if (val == 1) {
                          $('#contest-details-wrap-mini').css({
                            'visibility':'visible',
                            'opacity':'1'
                          });
                          val = 0;
                      }
                      else {
                          val = 1;
                          $('#contest-details-wrap-mini').css({
                            'visibility':'hidden',
                            'opacity':'0'
                          });
                      }
                      return false;
                    });
                

               $(".contest-detail-content-wrap #prize-open-btn").click(function(){
                        if (val === 1) {
                            $(this).siblings('.prize-list').css({
                            'visibility':'visible',
                            'opacity':'1',
                            'height':'100%'
                          });
                            $(this).css('transform','rotate(-180deg)');
                            val = 0;
                        }

                        else {
                            val = 1;
                            $(this).siblings('.prize-list').css({
                            'visibility':'hidden',
                            'opacity':'0',
                            'height':'0'
                          });
                            $(this).css('transform','rotate(0deg)');
                        }

                        return false;
                    });
               });
            },
            error:function(result){
                console.log('error: ' + result);
            }
        });
    });
</script>

{% endblock %}

templates/contest/tag_search_results-tr.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Contests{% endblock %}

{% block body %}


<section id="contest-list-result">
    <div class="inner-more">
        <div id="indexcontainer" class="container">
            <hr>
            <div id="1" class="row contest-list-item" style="visibility: hidden">

                    <div class="col-lg-3">
                        <div class="contest-img-wrap">
                            {% if request.user.is_authenticated %}
                                <div class="overlay">
                                    <form action="">
                                        <input class="btn btn-fill" type="submit" value="Enter Now">
                                    </form>
                                </div>
                            {% endif %}
                            <img class="topic-photo" src="">
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="contest-detail-wrap">
                            <h5></h5>
                            <p>Everybody wants to see your new photos only images uploaded.</p>
                            <span class="contest-tags"> </span>
                            <div class="button-wrap">
                                <a href="" class="btn btn-fill">Read More</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-sm-4">
                        <div class="contest-date-wrap">
                            <span class="contest-item-icon"><img src="{% static 'images/icons/calender.png' %}">Deadline</span>
                            <p></p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-sm-4">
                        <div class="contest-photo-count-wrap">
                            <span class="contest-item-icon"><img src="{% static 'images/icons/album.png' %}">Photos</span>
                            <p></p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-sm-4">
                        <div class="contest-prize-wrap">
                        <span class="contest-item-icon"><img src="{% static 'images/icons/trophy.png' %}">Prize Pool</span>
                        <p></p>
                        </div>
                    </div>
        </div>

    </div>
</section>

<script>
    $(document).ready( function(){

       $.ajax({
           url: '{% url "contest_api:tag" slug %}',
           type: 'GET',
           dataType: 'JSON',
           success: function(result){
               console.log(result);
               if (result['count'] > 0 )
                $("#1").css({'visibility': 'visible'});

               //Cloning divs
               for(var i=2; i<=result['results'].length; i++){
                   var clonedDiv = $( "#1" ).clone().appendTo( "#indexcontainer" );
                   clonedDiv.attr("id", i);
               }


                var idholder = 1;
                $.each(result['results'], function(index, value){ //contestler dönüyor
                  var getContestDate = new Date(value["end_date"]);  // Get Contest End Date in ISO Format
                  var tagAsStr = '';

                  $.each(value['tag'], function(index, data){ //taglar dönüyor
                      tagAsStr += "<a href='{% url 'contest:tag_search_list' slug='beyaz' %}'>" + "#" + data.title + "</a>" + "<br>";
                  });

                  year = getContestDate.getFullYear();
                  month = getContestDate.getMonth();
                  dt = getContestDate.getDate();

                  //add 0 if date,months are not 2 digits
                  if (dt<10) {
                    dt = '0' + dt;
                  }

                  var monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];  //Change month number to String
                  contestEndDate = monthNames[month] + ' ' + dt + 'th  ' + year;  //COnverted to Short Date Format


                $("#"+idholder+" .topic-photo").attr("src",value['topic_photo']);
                $("#"+idholder+" h5").html(value['contest_name']);
                $("#"+idholder+" .contest-tags").html(tagAsStr);
                $("#"+idholder+" .contest-date-wrap p").html(contestEndDate);
                $("#"+idholder+" .contest-photo-count-wrap p").html(value['photo_count']);
                $("#"+idholder+" .contest-prize-wrap p").html(value['prize_pool']+'$');
                $("#"+idholder+" form").attr("action","../" + value['slug'] + '/upload/');
                $("#"+idholder+" .button-wrap a").attr("href","../" + value['slug']);
                idholder++;
                });

           },
           error: function(data){
               console.log("Error");
           }
       });

    });
</script>


{% endblock %}