Photash/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^$', home_view, name = 'home'),

    url(r'^home/', include('home.urls', namespace="home")),

    url(r'^photo/', include('photo.urls', namespace="photo")),

    url(r'^contest/', include('contest.urls')),

    url(r'^user/', include('user.urls')),

    url(r'^admin/', admin.site.urls),

    path('api/report-photo/', include('reportedPhotos.api.urls', namespace='reportedPhotos_api')),
    path('api/photo/', include('photo.api.urls', namespace='photo_api')),
    path('api/user/', include('user.api.urls', namespace='user_api')),
    path('api/contest/', include('contest.api.urls', namespace='contest_api')),

    path('oauth/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

contest/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "contest"

urlpatterns = [

    url(r'^(?P<slug>[\w-]+)/photos/$', contest_photopool, name="photopool"),
    url(r'^(?P<slug>[\w-]+)/upload/$', photo_upload, name="photo_upload"),
    url(r'^index/$', contest_index, name="index"),
    path('tag/<slug:slug>/', tag_search_list, name='tag_search_list'),
    url(r'^(?P<slug>[\w-]+)/$', contest_detail, name='detail'),  # Aslında template içinde bu url çağırılmıyor. Çünkü template içinde url ismini vererek çağırırken parametre vermeyi başaramadım. eğer sonra düzeltirsem diye, url'e de slug koydum.
    # url(r'^create/$', photo_create), CONTEST OLUŞTURMAK ŞİMDİLİK USER TARAFINDAN YAPILAMAYACAGI İÇİN NE FORM NE DE VİEW YAZACAĞIM (SANIRIM)
    url(r'^(?P<id>\d+)/delete/$', contest_delete),
    url(r'^(?P<slug>[\w-]+)/rankings/$', contest_rankings, name='rankings'),

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "home"

urlpatterns = [
    url(r'^catalogue/$', catalogue_view, name='catalogue'),
]

user/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "user"

urlpatterns = [

    url(r'^login/$', login_view, name="login"),
    #url(r'^register/$', register_view, name="register"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^profile/$', profile_view, name="profile"),
    url(r'^profile/(?P<username>\w+)/$', myprofileview, name="detail_profile"),
    url(r'^editprofile/$', update_profile, name="updateprofile"),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})', activate_account, name='activate_account'),
    path('activate/<uidb64>/<token>/', activate_account, name="activate_account"),


]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <link rel="alternate" href="http://alercelik.pythonanywhere.com/" hreflang="en" />   <!--Domain ismi değişir. Ve sadece base'de değil her sayfada eklemek gerekebilir -->
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %} "/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    {% block css %}

    {% endblock %}

    <link href="https://fonts.googleapis.com/css?family=Raleway:200i,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:200,200i,300,300i,400,400i" rel="stylesheet">
    {% block first_scripts %}
    {% endblock %}
</head>
<body>

{% if not user.is_authenticated and "en" == request.session.language  %}
    {% include 'header.html' %}
{% endif %}
{% if not user.is_authenticated and "en" != request.session.language %}
    {% include 'header-tr.html' %}
{% endif %}

{% if user.is_authenticated %}
    {% if user.profile.languagePreference == "en" %}
        {% include 'header.html' %}
    {% endif %}
    {% if user.profile.languagePreference != "en" %}
        {% include 'header-tr.html' %}
    {% endif %}
{% endif %}

{% include 'messages.html' %}

    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.fancybox.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mobile.custom.min.js' %}"></script>

{% block body %}

{% endblock %}
{% include 'footer.html' %}

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/scripts.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/main-script.js'%}"></script>
    {% block scripts %}
    {% endblock %}



</body>
</html>

templates/footer.html
{% load static %}

<footer>
	<div class="inner-least">
		<div class="container">
			<div class="footer-item-wrap">
				<p><b>Photash</b> &copy; 2018</p>
				<ul class="footer-links">
					<li><a href="#">About</a></li>
					<li><a href="#">Users Agreements</a></li>
				</div>
			</div>
		</div>
	</div>
</footer>

templates/header-tr.html
{% load static %}


      <nav class="main-nav navbar navbar-expand-lg fixed-top navbar-light bg-light">
          <div class="container">
              <a class="navbar-brand d-flex align-items-center" href="#">
                <img id="logom" src="{% static 'images/logo-dark.png' %}" alt="Photash"/>
                <span>Photash</span>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'home' %}">{% if user.is_authenticated %} Olay Akışım {% endif %} {% if not user.is_authenticated %} Anasayfa {% endif %}</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'home:catalogue' %}">Katalog</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="{% url "contest:index" %}">Yarışmalar</a>
                    </li>

                     {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">Üye Girişi</a>
                        </li>
                     {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-chevron-down"></i> </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">İstatistikler</a></li>
                                <li><a href="#">Ayarlar</a></li>
                                <li><a href="{% url 'user:logout'%}">Çıkış</a></li>
                                <span class="menu-arrow-up"></span>
                            </ul>
                        </li>
                        <li class="nav-item nav-item-user">
                            <a class="nav-link" href="{% url 'user:profile' %}">{{ request.user.get_username }} <i class="fa fa-user-circle"></i></a>
                        </li>
                     {% endif %}

                  </ul>
              </div>
          </div>
      </nav>

templates/header.html
{% load static %}


      <nav class="main-nav navbar navbar-expand-lg fixed-top navbar-light bg-light">
          <div class="container">
              <a class="navbar-brand d-flex align-items-center" href="#">
                <img id="logom" src="{% static 'images/logo-dark.png' %}" alt="Photash"/>
                <span>Photash</span>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'home' %}">{% if user.is_authenticated %} Timeline {% endif %} {% if not user.is_authenticated %} Home {% endif %}</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'home:catalogue' %}">Catalogue</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="{% url "contest:index" %}">Contests</a>
                    </li>

                     {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                        </li>
                     {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-chevron-down"></i> </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Statistics</a></li>
                                <li><a href="#">Settings</a></li>
                                <li><a href="{% url 'user:logout'%}">Logout</a></li>
                                <span class="menu-arrow-up"></span>
                            </ul>
                        </li>
                        <li class="nav-item nav-item-user">
                            <a class="nav-link" href="{% url 'user:profile' %}">{{ request.user.get_username }} <i class="fa fa-user-circle"></i></a>
                        </li>
                     {% endif %}

                  </ul>
              </div>
          </div>
      </nav>

templates/messages.html
{% if messages %}
    <div class="content" style="margin-top:100px;">
        {% for message in messages %}
            <div class="{{ message.tags }}">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/register_form.html
{% load bootstrap3 %}
{% load static %}
<form method="POST" enctype="multipart/form-data" class="form-group">
    {% csrf_token %}
    {% for field in register_form %}
        {% if field.label == "First Name" %}
            <div class="row">
                <div class="col-lg-6">
                    <label for="first_name">{{ field.label }}</label>
                    {{ field }}
                </div>

        {% endif %}
        {% if field.label == 'Last Name' %}
                <div class="col-lg-6">
                    <label for="last_name">{{ field.label }}</label>
                    {{ field }}

                </div>

            </div>
        {% endif %}
    {% endfor %}
    {% bootstrap_form register_form exclude='first_name, last_name' %}
    <div class="home-form-btn-wrapper">
        <p class="agreement-info">By clicking Join now you agree to the Photash User Agreement,<br> Privacy Policy, and Cookie Policy.</p>
        <button class="btn btn-fill btn-full">Join Now</button>
        <span>Already have a Photash account? <a href="{% url 'user:login' %}">Log In</a></span>
        <div class="signup-with-wrapper">
            <p>
                <a>Sign Up</a> with
                <!--<a href="#" class="social-link">
                    <img src="{% static 'images/icons/fb.png' %}">
                </a>
                <a href="#" class="social-link">
                    <img src="{% static 'images/icons/google.png' %}">
                </a>-->
                <a href="http://127.0.0.1:8000/oauth/twitter/login/" class="social-link">
                    <img src="{% static 'images/icons/Twitter_Logo_Blue.png' %}">
                </a>
            </p>
        </div>
    </div>
</form>